### ISSUE TITLE
Add CI to automatically validate the reclass model on each commit

### ISSUE THREAD

**Issue by samos123** [Mirantis/mk-lab-salt-model#44]
Run reclass-salt --top or reclass-salt --pilar on each commit to make sure the branch is always in working state. This helps improve quality of each commit and prevents typos from going into master / dash branches.

Preferably in the future all changes go through pull request which trigger the CI and only if it gets through we merge changes into branches.

**Comment by epcim** [comment]
I am working on it right now.

**Comment by fpytloun** [comment]
We already have these jobs (see jenkins.tcpcloud.eu Reclass test view if you have access)

**Comment by epcim** [comment]
Have a look on #45 for some attempt. I fund my travis is now not free.

**Comment by epcim** [comment]
[**@fpytloun**](https://github.com/fpytloun) commented on [Nov 3, 2016, 9:30 PM GMT+1](https://github.com/Mirantis/mk-lab-salt-model/issues/44#issuecomment-258264626 "2016-11-03T20:30:12Z - Replied by Github Reply Comments"):
> We already have these jobs (see jenkins.tcpcloud.eu Reclass test view if you have access)


[**@fpytloun**](https://github.com/fpytloun) commented on [Nov 3, 2016, 9:30 PM GMT+1](https://github.com/Mirantis/mk-lab-salt-model/issues/44#issuecomment-258264626 "2016-11-03T20:30:12Z - Replied by Github Reply Comments"):
> We already have these jobs (see jenkins.tcpcloud.eu Reclass test view if you have access)

is our internal Jenkis capable of running tests and provide status to github PR?
If yes, we will need a new job for that, as new models has diferent structure and basically contain multiple salt-master's definitions. See more here: https://github.com/Mirantis/mk-lab-salt-model/pull/45/commits/e9d43f7c64c40bc47c03772eed752328fba7878a#diff-beb47b997873a329c78b3522091876ffR123

**Comment by fpytloun** [comment]
This is script which does the testing:
https://git.tcpcloud.eu/jenkins-jobs/cloudlab-jobs/blob/master/reclass-test/test_reclass.sh

IMHO it's really structure-independent as it will only spin up salt master into docker container, execute states to setup formulas, generate nodes, etc. and finally runs reclass-salt to render each node's pillar data.

**Comment by epcim** [comment]
CC @samos123 
Check #66 - local, per model verification.
